In [3]:
import os
import sys
import time

import pandas as pd
import numpy as np

import HTSeq as hs
import allel

In [5]:
print(os.listdir('./data/freebayes_output/temp'))

['var.vcf.gz.tbi.txt', 'var.vcf', 'var.vcf.gz']


In [6]:
callset = allel.read_vcf('./data/freebayes_output/temp/var.vcf')

In [7]:
sorted(callset.keys())

['calldata/GT',
 'samples',
 'variants/ALT',
 'variants/CHROM',
 'variants/FILTER_PASS',
 'variants/ID',
 'variants/POS',
 'variants/QUAL',
 'variants/REF']

In [8]:
callset['samples']

array(['S1'], dtype=object)

In [9]:
callset['variants/CHROM']

array(['1', '1', '1', ..., 'GL000221.1', 'GL000221.1', 'GL000221.1'],
      dtype=object)

In [10]:
callset['variants/POS']

array([ 326349, 2822908, 2823124, ...,   59276,   59283,   59332],
      dtype=int32)

In [11]:
callset['variants/QUAL']

array([1.60119e-02, 7.62502e-06, 3.93695e+00, ..., 5.84188e-05,
       5.87648e-05, 5.87513e-05], dtype=float32)

In [12]:
callset['calldata/GT']

array([[[1, 1]],

       [[0, 1]],

       [[0, 1]],

       ...,

       [[1, 1]],

       [[1, 1]],

       [[1, 1]]], dtype=int8)